export default [
  {
    title: "Covid-19 Latest Updates",
    image:
      "https://images.unsplash.com/photo-1516559828984-fb3b99548b21?ixlib=rb-1.2.1&auto=format&fit=crop&w=2100&q=80",
    cta: "View article",
    horizontal: true,
    from: "articles",
    content:
      "SINGAPORE: Singapore reported 179 new locally transmitted. COVID-19 infections as of noon on Wednesday (Jul 21), with 130 cases linked to the Jurong Fishery Port cluster and eight belonging to the KTV lounges cluster. There are now 454 cases linked to the Jurong Fishery Port/Hong Lim Market & Food Centre cluster, making it the largest active cluster in the country. A total of 215 cases have been linked to the KTV lounges cluster. Among the new cases announced on Wednesday, 149 are linked to previous infections, with 80 already placed in quarantine and 69 detected through surveillance testing. The remaining 30 infections were not linked to previous cases, said the Ministry of Health (MOH) in its subsequent update. Four of the new cases were seniors above 70 years old who were not vaccinated and are at risk of serious illness, said MOH. There were also two imported infections, who were placed on stay-home notice or isolated upon arrival. Both developed the illness during the stay-home notice or isolation period. In total, there were 181 new cases of COVID-19 in Singapore on Wednesday. MARINA BAY SANDS CASINO CLOSED Two new clusters have been identified: The Marina Bay Sands Casino cluster with a total of 11 cases and the Case 65231 cluster with four infections. MOH did not provide further information on Case 65231. There are currently 28 active clusters in Singapore, ranging between three and 454 infections. MOH said it is investigating cases of COVID-19 infection involving individuals who worked in or visited Marina Bay Sands Casino. Eleven cases have been linked to the cluster so far and MOH said its epidemiological investigations have found that there is likely ongoing transmission at the casino. To break the chain of transmission and enable deep cleaning of the premises, Marina Bay Sands Casino will be closed to all members of the public from Jul 22 to Aug 5. Special testing operations for all staff members of the casino will be conducted. Free COVID-19 testing will also be extended to members of the public who had visited Marina Bay Sands Casino between Jul 7 and Jul 21.",
  },
  {
    title: "How to keep fit during the pandemic",
    image:
      "https://images.unsplash.com/photo-1519368358672-25b03afee3bf?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2004&q=80",
    cta: "View article",
    from: "articles",
    content:
      "SINGAPORE: Singapore reported 179 new locally transmitted. COVID-19 infections as of noon on Wednesday (Jul 21), with 130 cases linked to the Jurong Fishery Port cluster and eight belonging to the KTV lounges cluster. There are now 454 cases linked to the Jurong Fishery Port/Hong Lim Market & Food Centre cluster, making it the largest active cluster in the country. A total of 215 cases have been linked to the KTV lounges cluster. Among the new cases announced on Wednesday, 149 are linked to previous infections, with 80 already placed in quarantine and 69 detected through surveillance testing. The remaining 30 infections were not linked to previous cases, said the Ministry of Health (MOH) in its subsequent update. Four of the new cases were seniors above 70 years old who were not vaccinated and are at risk of serious illness, said MOH. There were also two imported infections, who were placed on stay-home notice or isolated upon arrival. Both developed the illness during the stay-home notice or isolation period. In total, there were 181 new cases of COVID-19 in Singapore on Wednesday. MARINA BAY SANDS CASINO CLOSED Two new clusters have been identified: The Marina Bay Sands Casino cluster with a total of 11 cases and the Case 65231 cluster with four infections. MOH did not provide further information on Case 65231. There are currently 28 active clusters in Singapore, ranging between three and 454 infections. MOH said it is investigating cases of COVID-19 infection involving individuals who worked in or visited Marina Bay Sands Casino. Eleven cases have been linked to the cluster so far and MOH said its epidemiological investigations have found that there is likely ongoing transmission at the casino. To break the chain of transmission and enable deep cleaning of the premises, Marina Bay Sands Casino will be closed to all members of the public from Jul 22 to Aug 5. Special testing operations for all staff members of the casino will be conducted. Free COVID-19 testing will also be extended to members of the public who had visited Marina Bay Sands Casino between Jul 7 and Jul 21.",
  },
  {
    title: "Benefits of Covid vaccine",
    image:
      "https://images.unsplash.com/photo-1500522144261-ea64433bbe27?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2102&q=80",
    cta: "View article",
    from: "articles",
    content:
      "SINGAPORE: Singapore reported 179 new locally transmitted. COVID-19 infections as of noon on Wednesday (Jul 21), with 130 cases linked to the Jurong Fishery Port cluster and eight belonging to the KTV lounges cluster. There are now 454 cases linked to the Jurong Fishery Port/Hong Lim Market & Food Centre cluster, making it the largest active cluster in the country. A total of 215 cases have been linked to the KTV lounges cluster. Among the new cases announced on Wednesday, 149 are linked to previous infections, with 80 already placed in quarantine and 69 detected through surveillance testing. The remaining 30 infections were not linked to previous cases, said the Ministry of Health (MOH) in its subsequent update. Four of the new cases were seniors above 70 years old who were not vaccinated and are at risk of serious illness, said MOH. There were also two imported infections, who were placed on stay-home notice or isolated upon arrival. Both developed the illness during the stay-home notice or isolation period. In total, there were 181 new cases of COVID-19 in Singapore on Wednesday. MARINA BAY SANDS CASINO CLOSED Two new clusters have been identified: The Marina Bay Sands Casino cluster with a total of 11 cases and the Case 65231 cluster with four infections. MOH did not provide further information on Case 65231. There are currently 28 active clusters in Singapore, ranging between three and 454 infections. MOH said it is investigating cases of COVID-19 infection involving individuals who worked in or visited Marina Bay Sands Casino. Eleven cases have been linked to the cluster so far and MOH said its epidemiological investigations have found that there is likely ongoing transmission at the casino. To break the chain of transmission and enable deep cleaning of the premises, Marina Bay Sands Casino will be closed to all members of the public from Jul 22 to Aug 5. Special testing operations for all staff members of the casino will be conducted. Free COVID-19 testing will also be extended to members of the public who had visited Marina Bay Sands Casino between Jul 7 and Jul 21.",
  },
  {
    title: "Bonus game points!",
    image:
      "https://images.unsplash.com/photo-1487222477894-8943e31ef7b2?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1326&q=80",
    cta: "View article",
    from: "articles",
    content:
      "SINGAPORE: Singapore reported 179 new locally transmitted. COVID-19 infections as of noon on Wednesday (Jul 21), with 130 cases linked to the Jurong Fishery Port cluster and eight belonging to the KTV lounges cluster. There are now 454 cases linked to the Jurong Fishery Port/Hong Lim Market & Food Centre cluster, making it the largest active cluster in the country. A total of 215 cases have been linked to the KTV lounges cluster. Among the new cases announced on Wednesday, 149 are linked to previous infections, with 80 already placed in quarantine and 69 detected through surveillance testing. The remaining 30 infections were not linked to previous cases, said the Ministry of Health (MOH) in its subsequent update. Four of the new cases were seniors above 70 years old who were not vaccinated and are at risk of serious illness, said MOH. There were also two imported infections, who were placed on stay-home notice or isolated upon arrival. Both developed the illness during the stay-home notice or isolation period. In total, there were 181 new cases of COVID-19 in Singapore on Wednesday. MARINA BAY SANDS CASINO CLOSED Two new clusters have been identified: The Marina Bay Sands Casino cluster with a total of 11 cases and the Case 65231 cluster with four infections. MOH did not provide further information on Case 65231. There are currently 28 active clusters in Singapore, ranging between three and 454 infections. MOH said it is investigating cases of COVID-19 infection involving individuals who worked in or visited Marina Bay Sands Casino. Eleven cases have been linked to the cluster so far and MOH said its epidemiological investigations have found that there is likely ongoing transmission at the casino. To break the chain of transmission and enable deep cleaning of the premises, Marina Bay Sands Casino will be closed to all members of the public from Jul 22 to Aug 5. Special testing operations for all staff members of the casino will be conducted. Free COVID-19 testing will also be extended to members of the public who had visited Marina Bay Sands Casino between Jul 7 and Jul 21.",
  },
  {
    title: "Community Engagement Programmes",
    image:
      "https://images.unsplash.com/photo-1482686115713-0fbcaced6e28?fit=crop&w=1947&q=80",
    cta: "View article",
    horizontal: true,
    from: "articles",
    content:
      "SINGAPORE: Singapore reported 179 new locally transmitted. COVID-19 infections as of noon on Wednesday (Jul 21), with 130 cases linked to the Jurong Fishery Port cluster and eight belonging to the KTV lounges cluster. There are now 454 cases linked to the Jurong Fishery Port/Hong Lim Market & Food Centre cluster, making it the largest active cluster in the country. A total of 215 cases have been linked to the KTV lounges cluster. Among the new cases announced on Wednesday, 149 are linked to previous infections, with 80 already placed in quarantine and 69 detected through surveillance testing. The remaining 30 infections were not linked to previous cases, said the Ministry of Health (MOH) in its subsequent update. Four of the new cases were seniors above 70 years old who were not vaccinated and are at risk of serious illness, said MOH. There were also two imported infections, who were placed on stay-home notice or isolated upon arrival. Both developed the illness during the stay-home notice or isolation period. In total, there were 181 new cases of COVID-19 in Singapore on Wednesday. MARINA BAY SANDS CASINO CLOSED Two new clusters have been identified: The Marina Bay Sands Casino cluster with a total of 11 cases and the Case 65231 cluster with four infections. MOH did not provide further information on Case 65231. There are currently 28 active clusters in Singapore, ranging between three and 454 infections. MOH said it is investigating cases of COVID-19 infection involving individuals who worked in or visited Marina Bay Sands Casino. Eleven cases have been linked to the cluster so far and MOH said its epidemiological investigations have found that there is likely ongoing transmission at the casino. To break the chain of transmission and enable deep cleaning of the premises, Marina Bay Sands Casino will be closed to all members of the public from Jul 22 to Aug 5. Special testing operations for all staff members of the casino will be conducted. Free COVID-19 testing will also be extended to members of the public who had visited Marina Bay Sands Casino between Jul 7 and Jul 21.",
  },
];
